#!/bin/bash
# Usage: jfd bootstrap-server
# Summary: Bootstrap the base box before running chef scripts.
# Help: You don't want to run this on your local work station. Run it on a VM
# or remote box.

source "$_JFD_LIB/utils.sh"


jfd="$_JFD_ROOT/bin/jfd"
main () {
  not_local "You probably don't want to run this script on your workstation."

  jfd update-system
  sudo apt-get install build-essential python-software-properties --assume-yes

  jfd install ruby || fail "Unable to install Ruby"

  jfd install chef || fail "Unable to install Chef"

  ensure_dir "/home/vagrant/build"
}

main $@
