#!/bin/bash
# Usage: jfd deploy <package> <domain_name>
# Summary: Deploy the specified package to a remote box.
# Help: The <domain_name> will probably be something like '192.168.1.127',
# 'massive.fwp-dyn.com' or 'massive-b.fwp-dyn.com'.
#
#   Packages:
#     toehold
#     jfd

source "$_JFD_LIB/utils.sh"

main () {
	local package="$1"
	local domain_name="$2"

	if [ -z $package ]; then
		fail "The <package> argument is required."
	fi

	if [ -z $domain_name ]; then
		fail "The <domain_name> argument is required."
	fi

	case "$package" in
	"toehold" )
	    remote_sync "$_JFD_ROOT" "vagrant@$domain_name:/tmp/"
		;;
	"jfd" )
	    remote_sync "$_JFD_ROOT/" "vagrant@$domain_name:/build/"
		;;
	* )
		echo "Invalid package '$package'. No action taken."
		exit 0
		;;
	esac

}

main $@
