#!/bin/bash
# Usage: jfd install <package_name>
# Summary: Install a declared package.
# Help: In most cases you probably want to precede this command with
# `jfd update-sytem`.
#   package_names:
#     ruby

RUBY_VERSION="1.9.3"
RUBYDIR=/tmp/ruby_install

source "$_JFD_LIB/utils.sh"

main () {
    local package=$1

	if [ -z $package ]; then
		fail "The <package> argument is required."
	fi

    case "$package" in
    "ruby" )
        install_ruby
        ;;
    * )
        echo "Invalid package '$package'. No action taken."
        exit 0
        ;;
    esac
}

install_ruby () {
    local url="http://rubyforge.org/frs/download.php/76729/rubygems-1.8.25.tgz"

    sudo apt-get install --assume-yes \
        curl \
        ruby-full

    # Remove the old Vagrant Ruby
    if [ -d "/opt/vagrant_ruby" ]; then
        sudo rm -rf /opt/vagrant_ruby
    fi

    if ! [ -d "$RUBYDIR" ]; then
        ensure_dir "$RUBYDIR"
        curl -# -L "$url" \
            | tar xzf - -C "$RUBYDIR" --strip-components=1 \
            || fail "Could not download RubyGems"
    fi

    cd "$RUBYDIR"
    sudo ruby setup.rb --no-format-executable

    rm -rf "$RUBYDIR"
}

main $@
