#!/bin/bash
# Usage: jfd install <package_name>
# Summary: Install a declared package.
# Help: In most cases you probably want to precede this command with
# `jfd update-sytem`.
#   package_names:
#     ruby

RUBY_VERSION="1.9.3"
RUBYDIR=/tmp/ruby_install

source "$_JFD_LIB/utils.sh"

main () {
  local package=$1

  if [ -z $package ]; then
    fail "The <package> argument is required."
  fi

  case "$package" in
  "ruby" )
    install_ruby
    ;;
  "chef" )
    install_chef
    ;;
  * )
    echo "Invalid package '$package'. No action taken."
    exit 0
    ;;
  esac
}

install_ruby () {
  # http://brightbox.com/docs/ruby/ubuntu/
  # python-software-properties must be installed first
  sudo apt-add-repository --assume-yes ppa:brightbox/ruby-ng
  sudo apt-get update
  sudo apt-get install --assume-yes ruby1.9.3
}

install_chef () {
  if ! [ $(command -v chef-solo) ]; then
    sudo gem install chef --no-ri --no-rdoc || fail "Unable to install chef."
  fi
}

main $@
