#!/bin/bash
# Usage: jfd deploy <package> <domain_name>
# Summary: Deploy the specified package to a remote box.
# Help: The <domain_name> will probably be something like '192.168.1.127',
# 'massive.fwp-dyn.com' or 'massive-b.fwp-dyn.com'.
#
#   Packages:
#     jfd

source "$_JFD_LIB/utils.sh"

rsync_opts="\
--recursive \
--compress \
--links \
--perms \
--times \
--omit-dir-times \
--owner \
--group \
--progress \
--human-readable \
--exclude=*.swp \
--exclude=*.pyc \
--exclude=*.tmproj \
--exclude=.DS_Store \
--exclude=._* \
--exclude=._*/ \
--exclude=TAGS \
--exclude=*.tags \
"

main () {
	local package="$1"
	local domain_name="$2"

	if [ -z $package ]; then
		fail "The <package> argument is required."
	fi

	if [ -z $domain_name ]; then
		fail "The <domain_name> argument is required."
	fi

	case "$package" in
	"jfd" )
		;;
	* )
		echo "Invalid package '$package'. No action taken."
		exit 0
		;;
	esac

	local src="$_JFD_ROOT"
	local dest="vagrant@$domain_name:/tmp"

	rsync $rsync_opts "$src" "$dest/"
}

main $@
