#!/bin/bash
# Usage: jfd build-devbox
# Summary: Build the base Vagrant devbox VM.
# Help: You don't want to run this on your local work station. Run it on a VM
# or remote box.

source "$_JFD_LIB/utils.sh"


jfd="$_JFD_ROOT/bin/jfd"
main () {
    not_local "You probably don't want to run this script on your workstation."

    jfd update-system
    sudo apt-get install build-essential --assume-yes

    jfd install ruby || fail "Unable to install Ruby"

    if ! [ $(command -v chef-solo) ]; then
        sudo gem install chef --no-ri --no-rdoc || \
            fail "Unable to install chef."
    fi

    if ! [ -d "/build" ]; then
        sudo mkdir -p -- "/build" ||  \
            fail "Unable to create /build directory"
    fi

		ensure_dir "/home/vagrant/build"
}

main $@
