#!/bin/bash
# Usage: devbox build
# Summary: Install dependencies and build the JFDI development virtual machine.
# Help: This script is only meant to be run on a virtual machine, never your
# local work station or laptop.

fail () {
    echo "$@" >&2
    exit 1
}

if [ "$(id -u)" == "0" ]; then
    fail "This script must not be run by root, or by sudo."
fi

# It would be best to have a fresh base box to start with (apt-get
# dist-upgrade, dkms, and VirtualBox Guest Additions already installed and
# updated to the most recent versions).

sudo apt-get update || fail "Unable to update package repository."
sudo apt-get install curl --assume-yes

if ! [ -d "/usr/local/rvm" ]; then
    \curl -L# https://get.rvm.io | sudo bash -s stable

    # Add the rvm users.
    sudo usermod --append --groups rvm vagrant

    # Giv 'em some dot files
    sudo cp /jfdi/dotfiles/.bashrc /home/vagrant/

    # Echo out the system requirements.
    /usr/local/rvm/bin/rvm requirements

    echo "Take note of the requirements listed by RVM above, and make sure 
they are included in the packages installed by libexec/devbox-build.
Then exit this VM, restart it, log back in, and run

  /jfdi/bin/devbox build"
		echo
    exit 0
else
    echo "RVM is already installed:"
    /usr/local/rvm/bin/rvm --version
fi

# Remove the old Ruby
if [ -d "/opt/vagrant_ruby" ]; then
    sudo rm -rf /opt/vagrant_ruby
    echo "Removed the old vagrant_ruby."
fi

echo "
Installing system depenendencies...
"

sudo apt-get --no-install-recommends --assume-yes install \
    bash \
    vim \
    tree \
    git-core \
    patch \
    bzip2 \
    build-essential \
    openssl \
    libreadline6 \
    libreadline6-dev \
    zlib1g \
    zlib1g-dev \
    libssl-dev \
    libyaml-dev \
    libsqlite3-dev \
    sqlite3 \
    libxml2-dev \
    libxslt-dev \
    autoconf \
    libc6-dev \
    libgdbm-dev \
    ncurses-dev \
    automake \
    libtool \
    bison \
    subversion \
    pkg-config \
    libffi-dev

rvm install 1.9.3

echo
echo "Build done."
