#!/bin/bash
# Usage: jfd system-update [--local]
# Summary: Run a bunch of scripts to update the operating system.
# Help: Use the --local option to install VirtualBox stuff on the local
# development environment.  You would not want to do this on a production box.
#
# OPTIONS
#   --local Install VirtualBox stuff on local dev box.

fail () {
    echo "$@" >&2
    exit 1
}

apt-get update || fail "Unable to update package repository."

apt-get dist-upgrade --fix-missing --assume-yes \
    || fail "Unable to upgrade installed packages."

# Install VirtualBox stuff if the --local flag is up.
if [ "$1" == "--local" ]; then
    apt-get install dkms --assume-yes \
        || fail "Unable to install DKMS."
    apt-get install virtualbox-guest-additions --assume-yes \
        || fail "Unable to install VirtualBox guest additions."
fi
