#!/bin/bash
# Usage: jfd deploy-pinfinity_co <domain_name>
# Summary: Deploy the Pinfinity.co website to the remote box.
# Help: The <domain_name> will probably be 'massive.fwp-dyn.com' or 'massive-b.fwp-dyn.com'.

source "$_JFD_LIB/utils.sh"

main () {
    local domain_name="$1"

    if [ -z $domain_name ]; then
        fail "The <domain_name> argument is required."
    fi

    local src="$_JFD_ROOT/webapps/pinfinity_co"
    local dest="vagrant@$domain_name:/webapps/pinfinity_co"

    remote_sync "$src/" "$dest/"
}

main $@
